### ISSUE TITLE
librados.h:3272:21: note: declared here

### ISSUE THREAD

**Issue by xszx** [gostor/gotgt#105]
ubuntu 18.04下无法完成编译。

 apt-get install librados-dev
 apt-get install librbd-dev
安装依赖后，
使用make 命令，提示

/usr/include/rados/librados.h:3272:21: note: declared here
 CEPH_RADOS_API void rados_read_op_omap_get_vals(rados_read_op_t read_op,

**Comment by carmark** [comment]
@xszx Could you please check the ceph version? We did test jewel CEPH version in our CI test.

**Comment by carmark** [comment]
By the way, you may try `make build-nocgo` to build without ceph.

**Comment by xszx** [comment]
> By the way, you may try `make build-nocgo` to build without ceph.

我用make build-nocgo 编译成功，按照例子配置了config.json，启动也没有什么问题，但是在windows下进行iscsi连接，控制台输出
INFO[0011] Target is connected to initiator: 192.168.1.218:63425
ERRO[0011] EOF
windows这边显示目标错误。

是我哪里配置出了问题？

**Comment by xszx** [comment]
刚才 翻了一下Dockerfile
运行了
apt-get install -y curl automake gcc make libcephfs-dev librbd-dev librados-dev，
make还是报错
