### ISSUE TITLE
Continuous relogins while running dd commands on exposed iSCSI LUNs

### ISSUE THREAD

**Issue by payes** [gostor/gotgt#26]
I am testing the gotgt to use in another project that add scale-out/replication support for block volumes. When I exposed a volume and did "dd" test, I kept seeing continuous re-logins in the gotgt logs.

## Steps to Reproduce:

- Start the gotgt process as described in README
- Discover and login to the LUN using iscsiadm:
```bash
 --sudo iscsiadm -m discovery -t sendtargets -p 127.0.0.1:3260
 --sudo iscsiadm -m node -l
```
- Get the newly attached device:
```bash
 --sudo iscsiadm -m session -P 3
```
- Write some data using dd command on the newly attached device:
```bash
 --sudo dd if=/dev/urandom of=/dev/sdb bs=4k count=1000
```
- Run the above dd command once again to get the relogin 

## Snippet of the logs

```bash
I1123 14:49:24.641125   12808 iscsid.go:189] rx handler: IOSTATE_RX_BHS
I1123 14:49:24.641164   12808 iscsid.go:250] got command:
Op: SCSI Data-Out (write)
Final = true
Immediate = false 
Data Segment Length = 8192
Task Tag = 63000000
AHS Length = 0
LUN = [0 0 0 0 0 0 0 0]
ExpectedDataLen = 0
CmdSN = 0
ExpStatSN = 84
Read = false 
Write = false 
CDB = 
I1123 14:49:24.641622   12808 common.go:207] io done *^@^@^@^T^@^@
^@^@^@^@^@^@^@^@
I1123 14:49:24.641878   12808 iscsid.go:588] 12
I1123 14:49:24.641905   12808 iscsid.go:189] rx handler: IOSTATE_RX_BHS
E1123 14:49:24.642398   12808 iscsid.go:779] unexpected cmd serial number: (97, 109)
I1123 14:49:37.165039   12808 iscsid.go:144] 127.0.0.1:3260
I1123 14:49:37.165098   12808 iscsid.go:145] Accepting ...
I1123 14:49:37.165146   12808 iscsid.go:150] connection is connected from 127.0.0.1:53032...
I1123 14:49:37.165178   12808 iscsid.go:138] Listening ...
I1123 14:49:37.165263   12808 iscsid.go:189] rx handler: IOSTATE_RX_BHS
I1123 14:49:37.415663   12808 iscsid.go:250] got command: 
Op: Login Request
Final = true
Immediate = true
Data Segment Length = 473 
Task Tag = 0
AHS Length = 0
ISID = 23d050000
Transit = true
Continue = false 
Current Stage = Login Operational Negotiation
Next Stage = Full Feature Phase 
I1123 14:49:37.415732   12808 iscsid.go:268] OpLoginReq
I1123 14:49:37.416104   12808 iscsid.go:572] CONN_STATE_KERNEL
I1123 14:49:37.416164   12808 iscsid.go:588] 12
I1123 14:49:37.416205   12808 iscsid.go:189] rx handler: IOSTATE_RX_BHS
```
Is anyone else also facing the same issue?

**Comment by carmark** [comment]
Hello @payes 

This project is under heavy development, this should be a regression, we will try to figure out and provide the feedback ASAP.

Thanks,

**Comment by payes** [comment]
Hi @carmark
 
Thanks for getting back and also for all the efforts in getting the gotgt developed.
I had a chance to dig a little more into this issue as part of my other project where I am using gotgt extensively. The issue is caused by ExpCmdSN, being incremented for SCSIOut packets.
Can you please review the pull request I have generated.

Thanks

**Comment by carmark** [comment]
merged your PR, thanks.
