### ISSUE TITLE
support SCSI/iSCSI Task Management

### ISSUE THREAD

**Issue by carmark** [gostor/gotgt#35]

**Comment by kmova** [comment]
Hi @carmark .. 

Thanks for starting this project!

https://github.com/openebs/gotgt is relying on this feature and we were about to pick this one for fixing, but wanted to check with you if you are already working on these P2 items.. 

regards
Kiran

**Comment by carmark** [comment]
Hello @kmova 

Yes, I have already started a little code, but I am busy on my daily work recently.  I will continue to do it next week, hope that I can release it in this month.

Regards,
-Lei

**Comment by kmova** [comment]
Thanks Lei.. for the very quick response! Please feel free to reach us for any help we can provide with respect to testing or review etc.,
