### ISSUE TITLE
add lock for SCSITargetService instance

### ISSUE THREAD

**Issue by carmark** [gostor/gotgt#65]
Now, the function of `NewSCSITargetService()` returned single instance in the daemon, we need to add a lock or use `sync.Once` to make sure the thread-security.

**Comment by tpaullee** [comment]
Now, the gotgt works in single thread, but will become multi-threaded when the cluster design is implemented.  There are several places to use that SCSITargetService instance to operate the resource (target or LU), so we have to maintain only one instance to be multi-thread safe.

**Comment by donaldt10ydt** [comment]
I am glad to take this issue.

**Comment by tpaullee** [comment]
This is resolved by pull request #69 that was committed on 12/18/2017.
Closed.
